LOG_FILE_PATH = "server_log.txt"

TCP_PROTOCOL = "tcp"
SAW_PROTOCOL = "saw"
GBN_PROTOCOL = "gbn"

LOCALHOST = "127.0.0.1"
LISTEN_PORT = 7878

MAX_FILE_SIZE_SUPPORTED_IN_BYTES = 2 ** 32 # 4GB
CHUNK_SIZE = 4096

ERROR_BYTES = b"\x01"

#copiadas de client
PATH_SIZE_BYTES = 1
FILE_SIZE_BYTES = 4
RESPONSE_STATUS_BYTES = 1
SERVER_PORT = 7878
DOWNLOAD = 0
UPLOAD = 1
PAYLOAD_SIZE_BYTES = 4
PACKET_SEQUENCE_BYTES = 4
PACKET_SIZE = 4096
MAX_PAYLOAD_SIZE = PACKET_SIZE - PACKET_SEQUENCE_BYTES - PAYLOAD_SIZE_BYTES
GBN_WINDOW_SIZE = 5
RETRY_LIMIT = 3
MAX_WAITING_TIME = 40
CHUNK_SEQ_NUMBER_BYTES = 4

ACCEPT_TIMEOUT_IN_SECONDS = 0.5
MAX_BUF_SIZE = 4096
