from lib.server.constants import TCP_PROTOCOL


PATH_SIZE_BYTES = 1
FILE_SIZE_BYTES = 4
RESPONSE_STATUS_BYTES = 1
SERVER_PORT = 7878
DOWNLOAD = 0
UPLOAD = 1
PAYLOAD_SIZE_BYTES = 4
PACKET_SEQUENCE_BYTES = 4
PACKET_SIZE = 4096
MAX_PAYLOAD_SIZE = PACKET_SIZE - PACKET_SEQUENCE_BYTES - PAYLOAD_SIZE_BYTES
GBN_WINDOW_SIZE = 5
RETRY_LIMIT = 3
MAX_WAITING_TIME = 40
OPERATION_BYTES = 1
SOCKET_TIMEOUT = 5
SAW_CONNECTION_MAX_TIME_WITHOUT_MESSAGES = 20
TCP_PROTOCOL = "tcp"
SAW_PROTOCOL = "saw"
GBN_PROTOCOL = "gbn"
